-- {"id":325240,"ver":"1.0.0","libVer":"1.0.0","author":"me","repo":"","dep":[]}
-- Generated by the Monogatari Extension Builder. Safe to edit by hand.

local baseURL = "https://novelfire.net/home"

local function fetchDocument(url)
	return GETDocument(url)
end


local function startsWith(value, prefix)
	return value:sub(1, #prefix) == prefix
end

local function urlEncode(value)
	return (tostring(value):gsub("[^%w%-_%.~]", function(c)
		return ("%%%02X"):format(c:byte())
	end))
end

local function absoluteURL(url)
	if url == nil then return "" end
	url = tostring(url)
	if url == "" then return "" end
	if startsWith(url, "http") then return url end
	if startsWith(url, "//") then return "https:" .. url end
	if startsWith(url, "/") then return baseURL .. url end
	return baseURL .. "/" .. url
end

-- Replaces {page}/{query} placeholders and resolves the result against baseURL.
local function fillTemplate(template, page, query)
	local url = template:gsub("{page}", function() return tostring(page or 1) end)
	if query ~= nil then
		url = url:gsub("{query}", function() return query end)
	end
	return absoluteURL(url)
end

local function selectFirst(root, selector)
	if root == nil or selector == nil or selector == "" then return nil end
	local ok, node = pcall(function() return root:selectFirst(selector) end)
	if ok then return node end
	return nil
end

local function selectAll(root, selector)
	if root == nil or selector == nil or selector == "" then return nil end
	local ok, nodes = pcall(function() return root:select(selector) end)
	if ok then return nodes end
	return nil
end

local function textOf(node)
	if node == nil then return "" end
	local ok, value = pcall(function() return node:text() end)
	if ok and value ~= nil then return tostring(value) end
	return ""
end

local function attrOf(node, name)
	if node == nil or name == nil or name == "" then return "" end
	local ok, value = pcall(function() return node:attr(name) end)
	if ok and value ~= nil then return tostring(value) end
	return ""
end

local function readValue(node, source, attrName)
	if source == "ATTR" then return attrOf(node, attrName) end
	return textOf(node)
end


local function parseListing(document)
	local results = {}
	local cards = selectAll(document, "li.novel-item")
	if cards == nil then return results end
	for i = 0, cards:size() - 1 do
		local card = cards:get(i)
		local title = readValue(selectFirst(card, ".novel-title"), "TEXT", "")
		local link = attrOf(selectFirst(card, "a"), "href")
		if link == "" then link = attrOf(card, "href") end
		local image = attrOf(selectFirst(card, "img"), "src")
		if image == "" or startsWith(image, "data:") then image = attrOf(selectFirst(card, "img"), "data-src") end
		if title ~= "" and link ~= "" then
			results[#results + 1] = Novel {
				title = title,
				link = absoluteURL(link),
				imageURL = absoluteURL(image)
			}
		end
	end
	return results
end


local LISTINGS = {
	Listing("Popular", true, function(data)
		local document = fetchDocument(fillTemplate("https://novelfire.net/genre-all/sort-new/status-all/all-novel?page={page}", data[PAGE]))
		return parseListing(document)
	end)
}


local function search(data)
	local query = urlEncode(data[QUERY] or "")
	local document = fetchDocument(fillTemplate("https://novelfire.net/search?keyword={query}&type=title", data[PAGE], query))
	return parseListing(document)
end


local function parseNovel(novelURL, loadChapters)
	local document = fetchDocument(absoluteURL(novelURL))

	local info = {
		title = readValue(selectFirst(document, "h1.novel-title.text2row"), "TEXT", ""),
		imageURL = absoluteURL(attrOf(selectFirst(document, "figure.cover img"), "src")),
		status = NovelStatus.UNKNOWN
	}
	if info.title == "" then info.title = textOf(selectFirst(document, "h1")) end

	local descriptionNodes = selectAll(document, "#info")
	if descriptionNodes ~= nil and descriptionNodes:size() > 0 then
		info.description = descriptionNodes:text()
	end

	local authorNodes = selectAll(document, "a.property-item span")
	if authorNodes ~= nil and authorNodes:size() > 0 then
		info.authors = map(authorNodes, function(node) return node:text() end)
	end

	local genreNodes = selectAll(document, "a.property-item")
	if genreNodes ~= nil and genreNodes:size() > 0 then
		info.genres = map(genreNodes, function(node) return node:text() end)
	end

	local statusText = textOf(selectFirst(document, "strong.ongoing")):lower()
	if statusText ~= "" then
		if statusText:find("ongoing", 1, true) or statusText:find("publishing", 1, true) or statusText:find("laufend", 1, true) then
			info.status = NovelStatus.PUBLISHING
		elseif statusText:find("complet", 1, true) or statusText:find("finished", 1, true) or statusText:find("abgeschlossen", 1, true) then
			info.status = NovelStatus.COMPLETED
		elseif statusText:find("hiatus", 1, true) or statusText:find("paused", 1, true) then
			info.status = NovelStatus.PAUSED
		end
	end

	if loadChapters then
		local chapters = {}
		local rows = selectAll(document, "li")
		if rows ~= nil then
			for i = 0, rows:size() - 1 do
				local row = rows:get(i)
				local chapterTitle = readValue(selectFirst(row, ".chapter-title"), "TEXT", "")
				local link = attrOf(selectFirst(row, "a"), "href")
				if link == "" then link = attrOf(row, "href") end
				if chapterTitle == "" then chapterTitle = "Chapter " .. tostring(i + 1) end
				if link ~= "" then
					chapters[#chapters + 1] = NovelChapter {
						title = chapterTitle,
						link = absoluteURL(link),
						order = i
					}
				end
			end
		end
		info.chapters = chapters
	end

	return NovelInfo(info)
end


local function getPassage(chapterURL)
	local document = fetchDocument(absoluteURL(chapterURL))
	local content = selectFirst(document, "#chapter-container")
	if content == nil then
		return "Chapter content was not found. Check the content selector (" .. "#chapter-container" .. ") in the extension builder."
	end
	return pageOfElem(content, true)
end


return {
	id = 325240,
	name = "FireNet",
	baseURL = baseURL,
	imageURL = "https://raw.githubusercontent.com/shosetsuorg/extensions/dev/icons/default.png",
	hasCloudFlare = false,
	hasSearch = true,
	chapterType = ChapterType.HTML,
	startIndex = 1,
	listings = LISTINGS,
	searchFilters = {},
	settings = {},

	parseNovel = parseNovel,
	getPassage = getPassage,
	search = search,
	isSearchIncrementing = false,
	updateSetting = function(id, value) end,
	shrinkURL = function(url)
		local escaped = baseURL:gsub("([%^%$%(%)%%%.%[%]%*%+%-%?])", "%%%1")
		return (url:gsub("^" .. escaped, ""))
	end,
	expandURL = function(url)
		return absoluteURL(url)
	end
}
